# Generated by Django 3.1.1 on 2020-09-14 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Hospital Name')),
                ('cac', models.CharField(max_length=100, verbose_name='CAC')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Hospital Phone Number')),
                ('address', models.CharField(max_length=100, verbose_name='Hospital Address')),
                ('local_government_area', models.CharField(choices=[('LAT115 LON117', 'Ilorin South'), ('LAT116 LON118', 'Ilorin North'), ('LAT119 LON111', 'Ilorin West')], max_length=100, verbose_name='LGA')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Detail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('other_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Name')),
                ('father_name', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('mother_name', models.CharField(max_length=100, verbose_name="Mother's Name")),
                ('doctor_name', models.CharField(max_length=100, verbose_name="Doctor's Name")),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Address')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15, verbose_name='Gender')),
                ('weight', models.CharField(max_length=15, verbose_name='Child Weight')),
                ('time_of_birth', models.TimeField(verbose_name='Time of Birth')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birth_rate_app.hospital', verbose_name="Child's Birth Hospital")),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
