# Generated by Django 3.1.1 on 2020-09-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birth_rate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='local_government_area',
            field=models.CharField(choices=[('8.4141872,4.1541288', 'Asa'), ('9.3710088,2.7151682', 'Baruten'), ('8.8443894,4.9197744', 'Edu'), ('8.1126934,5.2103039', 'Ekiti'), ('8.634559,4.7525483', 'Ifelodun'), ('8.5916408,4.6167261', 'Ilorin East'), ('8.4404134,4.5982463', 'Ilorin South'), ('8.4882947,4.462491', 'Ilorin West'), ('8.257908,4.9194132', 'Isin'), ('8.1942491,4.8238084', 'Irepodun'), ('9.607286,3.9218983', 'Kaiama'), ('8.8563905,4.2643653', 'Moro'), ('8.1499364,4.6780293', 'Offa'), ('8.1796551,5.1153793', 'Oke Ero'), ('8.2004612,4.5062674', 'Oyun'), ('8.7220741,5.739946', 'Pategi')], max_length=100, verbose_name='LGA'),
        ),
    ]
